## **AUTOMATED DATA CLEANING**

#### Types of Missing Data :

#### 1. Missing Completely At Random (MCAR)
#### 2. Missing At Random (MAR)
#### 3. Missing Not At Random (MNAR)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [3]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [5]:
df['User ID'].isnull().sum()

np.int64(201)

In [7]:
df=df.drop(columns=['User ID'])

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [9]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [11]:
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [12]:
### drop missing data --->  dropns()

In [13]:
### Mean/ Median Imputation ---> Fill the Missing Data with the Mean or Median of All Rows of that column

In [14]:
### While Going with Mean Value ----> Check for the Outliers

### Age--> 500 (Outlier) ----> 10000 --> mean --> ??
## Age ---> Median ----> if you arrange all values from low to high side 
## Age ----> Mode ---> Most frequency Age ----> Age

## 1,2,3,...,50,..100,...,500

In [15]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [16]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [17]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [18]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [19]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [21]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [22]:
df[df['Blood Oxygen Level (%)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [25]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

### Forward Filling (`ffill`) and Backward Filling (`bfill`) ---> Time Series Data

#### **Forward Filling (`ffill`) → Fill missing values using the previous available value.**

#### **Backward Filling (`bfill`) → Fill missing values using the next available value.**

### Example

**Original:**

`10 → NaN → NaN → 20`

**Forward Fill:**

`10 → 10 → 10 → 20`

**Backward Fill:**

`10 → 20 → 20 → 20`

### Pandas Syntax

```python
# Forward Fill
df['column'].ffill()

# Backward Fill
df['column'].bfill()