## **AUTOMATED DATA CLEANING**

#### Types of Missing Data :

#### 1. Missing Completely At Random (MCAR)
#### 2. Missing At Random (MAR)
#### 3. Missing Not At Random (MNAR)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [3]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [5]:
df['User ID'].isnull().sum()

np.int64(201)

In [7]:
df=df.drop(columns=['User ID'])

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [9]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [11]:
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [12]:
### drop missing data --->  dropns()

In [13]:
### Mean/ Median Imputation ---> Fill the Missing Data with the Mean or Median of All Rows of that column

In [14]:
### While Going with Mean Value ----> Check for the Outliers

### Age--> 500 (Outlier) ----> 10000 --> mean --> ??
## Age ---> Median ----> if you arrange all values from low to high side 
## Age ----> Mode ---> Most frequency Age ----> Age

## 1,2,3,...,50,..100,...,500

In [15]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [16]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [17]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [18]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [19]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [21]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [22]:
df[df['Blood Oxygen Level (%)'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [25]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

### Forward Filling (`ffill`) and Backward Filling (`bfill`) ---> Time Series Data

#### **Forward Filling (`ffill`) → Fill missing values using the previous available value.**

#### **Backward Filling (`bfill`) → Fill missing values using the next available value.**

### Example

**Original:**

`10 → NaN → NaN → 20`

**Forward Fill:**

`10 → 10 → 10 → 20`

**Backward Fill:**

`10 → 20 → 20 → 20`

### Pandas Syntax

```python
# Forward Fill
df['column'].ffill()

# Backward Fill
df['column'].bfill()

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [28]:
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [30]:
### method ---> ffill or bfill

df['Step Count']=df['Step Count'].fillna('ffill')

In [33]:
df['Step Count'].isnull().sum()

np.int64(0)

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  object
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(2), object(1), str(3)
memory usage: 468.9+ KB

In [35]:
df['Sleep Duration (hours)'].dtype

In [36]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,75.220601,98.532195,727.60161,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [39]:
df[df['Sleep Duration (hours)']=='ERROR']

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
62,115.078288,99.928041,1918.372142,ERROR,Highly_Active,4
71,64.799778,94.743857,4613.859266,ERROR,Highly_Active,10
81,41.709895,96.857347,1413.015778,ERROR,Highly_Active,4
92,70.243810,97.171134,2336.583406,ERROR,Highly Active,7
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,ERROR,Active,4
9912,75.933666,97.386073,1813.072248,ERROR,Sedentary,10
9927,87.579045,98.768633,3727.161872,ERROR,Active,1
9943,91.834863,96.145378,38831.465057,ERROR,Active,4
9951,70.335328,98.560133,1997.442874,ERROR,Highly_Active,9

In [40]:
### object ---> Numeric ---> pandas ---> to_numeric()

In [41]:
df['Sleep Duration (hours)']=pd.to_numeric(df['Sleep Duration (hours)'],errors='coerce')

In [42]:
df[df['Sleep Duration (hours)']=='ERROR']

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [44]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [45]:
df['Sleep Duration (hours)']

0       7.167236
1       6.538239
2            NaN
3       7.367790
4            NaN
          ...
9995    7.402749
9996    6.382166
9997    6.916549
9998    5.691234
9999    5.691001
Name: Sleep Duration (hours), Length: 10000, dtype: float64

In [46]:
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [47]:
df['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [48]:
df['Sleep Duration (hours)']=df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [49]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

In [50]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,75.220601,98.532195,727.60161,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,6.505463,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,6.505463,Highly_Active,6

In [51]:
### for Categorical Columns ---> Mode ---> Most Frequently repeating value in value column

In [52]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [53]:
df['Activity Level'].isnull().sum()

np.int64(200)

In [54]:
df['Activity Level']=df['Activity Level'].fillna('Seddentary')

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  object
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), object(1), str(2)
memory usage: 468.9+ KB

In [56]:
### Contstant Imputation ---> When ypu want to fill missing values with a constant like 'unknown',-999,0

In [57]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [58]:
df['Stress Level']=df['Stress Level'].fillna(5)

In [59]:
df['Stress Level'].info()

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: Stress Level
Non-Null Count  Dtype
--------------  -----
10000 non-null  object
dtypes: object(1)
memory usage: 78.3+ KB

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  object
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(2), str(1)
memory usage: 468.9+ KB

In [61]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [63]:
df=df.drop(columns=['User ID'])

In [ ]:
# %pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.5.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.1)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\abhis\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.25.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 7.2 MB/s eta 0:00:01
   --------------- ------------------------ 3.1/8.2 MB 9.7 MB/s eta 0:00:01
   ------------------- -------------------- 3.9/8.2 MB 7.6 MB/s eta 0:00:01
   ---------------------- ----------------- 4.7/8.2 MB 6.6 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.2 MB 5.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.2 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.4 MB/s  0:00:02
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, cloudpickle, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [cloudpickle]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed cloudpickle-3.1.2 joblib-1.6.0 scikit-learn-1.9.1 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')

In [71]:
df['Heart Rate (BPM)']=imputer.fit_transform(df[['Heart Rate (BPM)']])

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [73]:
imputer=SimpleImputer(strategy='mean')

In [74]:
df['Blood Oxygen Level (%)']=imputer.fit_transform(df[['Blood Oxygen Level (%)']])

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [76]:
impute=SimpleImputer(strategy='most_frequent')

In [78]:
df['Activity Level']=impute.fit_transform(df[['Activity Level']]).ravel()

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [80]:
impute=SimpleImputer(strategy='constant',fill_value=5)

In [82]:
df['Stress Level']=impute.fit_transform(df[['Stress Level']]).ravel()

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 468.9+ KB

In [85]:
imputer=SimpleImputer(strategy='mean')

In [86]:
df['Step Count']=impute.fit_transform(df[['Step Count']]).ravel()

In [87]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 468.9+ KB